### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by hyperupcall** [brpaz/vscode-contextual-snips#64] opened 2022-01-09 08:01 UTC
I'm not sure if there was an API change or what, but after I install the extension, I get a command not found once I try to use a command from the command pallete 
![image](https://user-images.githubusercontent.com/24364012/148674148-dd9fe8ef-50a4-4f36-a6c2-05feb1d615cf.png)

None of the following fixed the issue

- Refresh Editor
- Close and reopen editor

**Comment by brpaz** [comment] 2022-01-09 18:18
@hyperupcall this is an issue with the latest version of this extension. Will try to find the cause.

**Comment by anion155** [comment] 2022-05-06 19:12
Any updates?

**Comment by brpaz** [comment] 2022-06-04 14:05
This should be fixed in version 1.3.1

**Closed by brpaz** 2022-06-04 14:05 UTC
